version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: image-processing-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: image_processing
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - image-processing-network

  redis:
    image: redis:7-alpine
    container_name: image-processing-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - image-processing-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  image-processing-network:
    driver: bridge
